// web/src/routes/(protected)/knowledge/+page.svelte
<script lang="ts">
	import PageLayout from "$lib/components/page-layout.svelte";
	import KnowledgeTable from "$lib/features/knowledge/components/table/knowledge-table.svelte";
	import { knowledgeService } from "$lib/features/knowledge/service";

  const listQuery = knowledgeService.list();
  const knowledges = $derived(listQuery.data ?? []);
</script>

<PageLayout
	title="Knowledge"
	description="Manage your knowledge."
>
  <KnowledgeTable {knowledges} isLoading={listQuery.isLoading} />
</PageLayout>

// web/src/routes/admin/knowledge/page.tsx
import { Page } from "@/components/page";
import { KnowledgeList } from "@/features/knowledge/components/knowledge-list";

export function AdminKnowledgePage() {
  return (
    <Page
      title="Knowledge"
      description="Browse and manage knowledge sources."
      documentTitle="Knowledge"
    >
      <KnowledgeList />
    </Page>
  );
}
