// web/src/routes/admin/knowledge/page.tsx
import { Page, PageActions } from "@/components/page";
import { Button } from "@/components/ui/button";
import { CreateKnowledgeDialog } from "@/features/knowledge/components/create-knowledge-dialog";
import { KnowledgeList } from "@/features/knowledge/components/knowledge-list";
import { useDialog } from "@/lib/dialog/use-dialog";
import { Plus } from "lucide-react";

export function AdminKnowledgePage() {
  const { openDialog } = useDialog();

  const openCreate = () => {
    openDialog({
      component: CreateKnowledgeDialog,
      props: {},
    });
  };

  return (
    <Page
      title="Knowledge"
      description="Browse and manage knowledge sources."
      documentTitle="Knowledge"
    >
      <PageActions>
        <Button onClick={openCreate}>
          <Plus />
          Create Knowledge
        </Button>
      </PageActions>
      <KnowledgeList />
    </Page>
  );
}

// web/src/routes/manage/(protected)/(system)/knowledge/+page.svelte
<script lang="ts">
	import KnowledgeCreateDialog from "$lib/features/knowledge/components/knowledge-create-dialog.svelte";
	import PageLayout from "$lib/components/page-layout.svelte";
	import KnowledgeTable from "$lib/features/knowledge/components/tables/knowledge-table.svelte";
	import { knowledgeService } from "$lib/features/knowledge/service";
	import { PlusIcon } from "@lucide/svelte";

  const listQuery = knowledgeService.list();
  const knowledges = $derived(listQuery.data ?? []);
</script>

<PageLayout
	title="Knowledge"
	description="Manage your knowledge."
>
	{#snippet actionsRight()}
		<KnowledgeCreateDialog>
			{#snippet trigger()}
				<PlusIcon />
				Create knowledge
			{/snippet}
		</KnowledgeCreateDialog>
	{/snippet}
  <KnowledgeTable {knowledges} isLoading={listQuery.isLoading} />
</PageLayout>
