// web/src/routes/auth/api-key/page.tsx
import { ApiKeyLoginForm } from "@/features/api-key/components/api-key-login";

export const ApiKeyLoginPage = () => {
  return (
    <div className="flex min-h-svh flex-col items-center justify-center gap-6 bg-background p-6 md:p-10">
      <div className="w-full max-w-sm">
        <ApiKeyLoginForm />
      </div>
    </div>
  )
}

// web/src/routes/auth/api-key/+page.svelte
<script lang="ts">
	import PageHead from "$lib/components/page-head.svelte";
  import ApiKeyForm from "$lib/features/api-key/components/api-key-form.svelte";
</script>
<PageHead title="API Key Login" description="Login using an API key to access the API" />
<div class="flex h-screen w-full items-center justify-center px-4">
  <ApiKeyForm />
</div>
