// web/src/features/client/components/client-code.tsx
import { Button } from "@/components/ui/button";
import { useClipboard } from "@/hooks/use-clipboard";
import { CopyIcon } from "lucide-react";

export function ClientCode({ code }: { code: string }) {
  const { copy } = useClipboard();

  const handleCopy = (event: React.MouseEvent<HTMLButtonElement>) => {
    event.preventDefault();
    event.stopPropagation();
    copy(code, {
      successTitle: `Client code copied to clipboard`,
      successDescription: "The code has been copied to your clipboard.",
      errorTitle: "Failed to copy to clipboard",
      errorDescription: "Please try again.",
    });
  }

  return (
    <div className="flex flex-row items-center gap-2">
      <span className="text-sm text-muted-foreground">{code}</span>
      <Button variant="outline" size="icon-xs" aria-label="Copy code" onClick={handleCopy}>
        <CopyIcon className="size-3" />
      </Button>
    </div>
  )
}

// web/src/lib/features/client/components/client-code.svelte
<script lang="ts">
  import { Button } from "$lib/components/ui/button/index.js";
  import { CopyIcon } from "@lucide/svelte";
	import { toast } from "svelte-sonner";

  let { code, class: className }: { code: string | null | undefined, class?: string } = $props();

  function handleCopyCode(e: MouseEvent) {
    if (!code) return;
    e.preventDefault();
    e.stopPropagation();
    navigator.clipboard.writeText(code);
    toast.success("Client code copied.");
  }
</script>
{#if code}
  {code}
  <Button
    variant="outline"
    size="icon-xs"
    class={className}
    onclick={handleCopyCode}
    aria-label="Copy client code"
  >
    <CopyIcon class="size-2.5" />
  </Button>
{/if}
